<?php
class Diagioihanhchinh_Geo_Data_Importer {
	public function import() {
		$support_geodata_taxonomies = apply_filters(
			'diagioihanhchinh_administrative_area_level_1_support_geo_data',
			array()
		);
		if ( empty( $support_geodata_taxonomies ) ) {
			return;
		}

		global $wp_version;
		foreach ( $support_geodata_taxonomies as $support_geodata_taxonomy ) {
			$args  = array(
				'taxonomy'   => $support_geodata_taxonomy,
				'hide_empty' => false,
				'orderby'    => 'ID',
			);
			$terms = version_compare( $wp_version, '4.5.0' ) ? get_terms( $args ) : get_terms( $args['taxonomy'], $args );
			$this->import_city_geodata( $terms );
		}
	}

	public function import_city_geodata( $terms ) {
		if ( empty( $terms ) ) {
			return;
		}
		foreach ( $terms as $term ) {
			$city_name = remove_accents( str_replace( 'TP ', '', $term->name ) );
			$city_name = str_replace( ' - ', ' ', $city_name );
			$this->read_geo_data_from_city_name( $city_name, $term );
		}
	}

	protected function group_ward_locations_to_districts( $kml_content ) {
		if ( empty( $kml_content ) ) {
			return;
		}

		$kml       = simplexml_load_string( $kml_content );
		$city_kml  = $kml->Document->Folder;
		$districts = array();

		foreach ( $city_kml->Placemark as $ward_kml ) {
			$district_name = (string) $ward_kml->ExtendedData->SchemaData->SimpleData;
			if ( ! isset( $districts[ $district_name ] ) ) {
				$district_key                = Diagioihanhchinh_Data::create_location_key_from_name( $district_name );
				$districts[ $district_name ] = array(
					'name' => $district_name,
					'key'  => $district_key,
				);
			}
			$districts[ $district_name ]['wards_kml'][] = $ward_kml->asXML();
		}

		return $districts;
	}

	public function read_geo_data_from_city_name( $name, $term ) {
		$plugin_dir      = dirname( DIAGIOIHANHCHINH_PLUGIN_FILE );
		$kml_dir         = sprintf( '%s/outputs/kml', $plugin_dir );
		$cached_kml_file = sprintf( '%s/%s.kml', $kml_dir, $name );

		if ( ! file_exists( $cached_kml_file ) ) {
			$data_file = sprintf( '%s/data/kml/%s.kmz', $plugin_dir, $name );
			if ( ! file_exists( $data_file ) ) {
				error_log(
					sprintf(
						'Lỗi cập nhật geo data cho %s: lỗi tập tin data  "%s" không tồn tại',
						$name,
						$data_file
					)
				);
				return false;
			}
			$zip = new ZipArchive();
			$res = $zip->open( $data_file );
			if ( $res === true ) {
				$zip->extractTo( $kml_dir );
				$zip->close();
				rename(
					sprintf( '%s/doc.kml', $kml_dir ),
					$cached_kml_file
				);
			} else {
				error_log( sprintf( 'Không thể mở tập tin "%s"', $data_file ) );
				return false;
			}
		}

		$kml_content  = file_get_contents( $cached_kml_file );
		$parser       = new KML();
		$multipolygon = $parser->read( $kml_content, true );

		do_action(
			"diagioihanhchinh_insert_{$term->taxonomy}_term_geodata",
			$multipolygon,
			$term,
			$kml_content,
			$cached_kml_file
		);

		$grouped_district_geodatas = $this->group_ward_locations_to_districts( $kml_content );
		$this->read_district_geodatas( $grouped_district_geodatas, $term->taxonomy, $term->name );
	}


	protected function read_district_geodatas( $grouped_district_geodatas, $taxonomy, $city_name ) {
		if ( empty( $grouped_district_geodatas ) ) {
			return;
		}

		foreach ( $grouped_district_geodatas as $district_geodata ) {
			$wards_kml     = implode( "\n", $district_geodata['wards_kml'] );
			$district_name = $district_geodata['name'];

			$kml_content = <<<XML
<?xml version="1.0" encoding="UTF-8"?>
	<!-- Generated by Puleeno Nguyen 2020 -->
	<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:gx="http://www.google.com/kml/ext/2.2">
		<Document>
			<name>{$district_name}</name>
			<atom:author>
				<atom:name>Puleeno Nguyen</atom:name>
				<atom:email>puleeno@gmail.com</atom:email>
			</atom:author>
			<visibility>1</visibility>
			<Schema name="NewFeatureType" id="NewFeatureType">
				<SimpleField type="xsd:string" name="Quan" />
			</Schema>
			<Folder id="kml_ft_{$district_geodata['key']}">
				<name>{$district_name}</name>
				{$wards_kml}
			</Folder>
		</Document>
	</kml>
XML;

			$parser       = new KML();
			$multipolygon = $parser->read( $kml_content, true );

			do_action(
				"diagioihanhchinh_insert_{$taxonomy}_districts_term_geodata",
				$multipolygon,
				$district_name,
				$city_name,
				$taxonomy,
				$kml_content
			);
		}
	}
}
